# Generated by Django 4.2 on 2024-11-03 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_user_username_alter_user_email'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='incharge',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='institution', to='core.userprofile'),
        ),
    ]
