# Generated by Django 4.2 on 2024-11-17 06:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='contact_no',
            field=models.CharField(db_index=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator('^\\d{10,12}$', 'Enter a valid contact number')]),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, null=True, unique=True),
        ),
    ]
