# Generated by Django 4.2 on 2025-01-29 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_organisation_area_organisation_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='busrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
