# Generated by Django 4.2 on 2024-11-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_stop_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='stops',
            field=models.ManyToManyField(related_name='stops', to='services.stop'),
        ),
    ]
