# Generated by Django 4.2 on 2024-11-14 10:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_bus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='contact_no',
            field=models.CharField(db_index=True, max_length=12, validators=[django.core.validators.RegexValidator('^\\d{10,12}$', 'Enter a valid contact number')]),
        ),
    ]
