# Generated by Django 4.2 on 2025-01-29 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_busrequest_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2002-10-20 12:12'),
            preserve_default=False,
        ),
    ]
