# Generated by Django 4.2 on 2024-11-19 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_route_stops'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('instructions', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('code', models.CharField(max_length=100, null=True, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='services.organisation')),
                ('stops', models.ManyToManyField(related_name='registration_stops', to='services.stop')),
            ],
        ),
    ]
