# Generated by Django 4.2 on 2025-01-20 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_bus_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop',
            name='registration',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='services.registration'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stop',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisations', to='services.organisation'),
        ),
    ]
