# Generated by Django 4.2 on 2025-01-30 04:42

import config.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import services.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0004_alter_busrequest_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=services.models.rename_bus_uploaded_file, validators=[config.validators.validate_excel_file])),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.organisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
