# Generated by Django 4.2 on 2025-01-30 04:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_busfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='busfile',
            name='added',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='busfile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='busfile',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='busfile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
