# Generated by Django 4.2 on 2024-11-20 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('services', '0005_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='incharge',
            field=models.OneToOneField(max_length=200, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.userprofile'),
        ),
    ]
