# Generated by Django 4.2 on 2025-01-20 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_stop_org_alter_stop_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='registration',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='services.registration'),
            preserve_default=False,
        ),
    ]
