# Generated by Django 4.2 on 2024-11-20 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_institution_incharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.route'),
        ),
    ]
