# Generated by Django 4.2 on 2025-01-30 05:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_busfile_added_busfile_created_at_busfile_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='busfile',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
