# Generated by Django 4.2 on 2025-01-20 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_schedule_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='stops',
        ),
    ]
