# Generated by Django 4.2 on 2024-11-21 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_timeslot_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='time_slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buses', to='services.timeslot'),
        ),
    ]
