# Generated by Django 4.2 on 2025-01-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_organisationactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='registration_no',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
