# Generated by Django 4.2 on 2025-01-20 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_remove_registration_stops'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='services.organisation'),
        ),
        migrations.AlterField(
            model_name='stop',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='services.registration'),
        ),
    ]
