# Generated by Django 4.2 on 2024-11-24 06:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_bus_time_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='alternative_contact_no',
            field=models.CharField(default=1, max_length=12, validators=[django.core.validators.RegexValidator('^\\d{10,12}$', 'Enter a valid contact number')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='recipt_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='student_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
