# Generated by Django 4.2 on 2025-01-31 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_alter_bus_registration_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
