# Generated by Django 4.2 on 2025-01-20 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_alter_stop_org_alter_stop_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stop',
            name='map_link',
        ),
    ]
