# Generated by Django 4.2 on 2025-02-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_receipt_is_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='registration_no',
            field=models.CharField(max_length=100),
        ),
    ]
