# Generated by Django 4.2 on 2024-11-25 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_alter_institution_incharge'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('Institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='services.institution')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='services.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='Recipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipt_id', models.CharField(max_length=500)),
                ('student_id', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('Institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipts', to='services.institution')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipts', to='services.organisation')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipts', to='services.registration')),
                ('student_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.studentgroup')),
            ],
        ),
    ]
