# Generated by Django 4.2 on 2025-01-21 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_remove_stop_map_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20)),
                ('pickup_booking_count', models.PositiveIntegerField(default=0)),
                ('drop_booking_count', models.PositiveIntegerField(default=0)),
                ('total_available_seats', models.PositiveIntegerField()),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='bus',
            name='registration_no',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.DeleteModel(
            name='BusCapacity',
        ),
        migrations.AddField(
            model_name='busrecord',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacities', to='services.bus'),
        ),
        migrations.AddField(
            model_name='busrecord',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_capacities', to='services.registration'),
        ),
        migrations.AddField(
            model_name='busrecord',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.route'),
        ),
        migrations.AlterUniqueTogether(
            name='busrecord',
            unique_together={('bus', 'registration')},
        ),
    ]
