# Generated by Django 4.2 on 2024-11-26 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_studentgroup_recipt'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recipt',
            new_name='Receipt',
        ),
        migrations.RenameField(
            model_name='receipt',
            old_name='recipt_id',
            new_name='receipt_id',
        ),
    ]
