# Generated by Django 4.2 on 2025-02-07 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_alter_receipt_receipt_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='stops',
        ),
        migrations.AddField(
            model_name='stop',
            name='route',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='services.route'),
            preserve_default=False,
        ),
    ]
