# Generated by Django 4.2 on 2025-01-24 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_busrecord_org_alter_busrecord_bus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busrecord',
            name='bus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='services.bus'),
        ),
    ]
