# Generated by Django 4.2 on 2024-11-26 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_rename_recipt_receipt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='Institution',
            new_name='institution',
        ),
    ]
