# Generated by Django 4.2 on 2025-01-26 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_alter_busrecord_bus'),
    ]

    operations = [
        migrations.AddField(
            model_name='busrecord',
            name='total_available_seats_percentage',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
