# Generated by Django 4.2 on 2024-11-26 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_rename_institution_receipt_institution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentgroup',
            old_name='Institution',
            new_name='institution',
        ),
    ]
