# Generated by Django 4.2 on 2025-02-07 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_alter_busrecord_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_one_way', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=500)),
                ('drop_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drop_groups', to='services.schedule')),
                ('pick_up_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_groups', to='services.schedule')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_groups', to='services.registration')),
            ],
        ),
    ]
