# Generated by Django 4.2 on 2024-11-27 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_rename_institution_studentgroup_institution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='recipt_id',
        ),
        migrations.AddField(
            model_name='ticket',
            name='recipt',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='services.receipt'),
            preserve_default=False,
        ),
    ]
