# Generated by Django 4.2 on 2025-01-26 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_remove_busrecord_total_available_seats_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busrecord',
            name='total_filled_seats_percentage',
        ),
    ]
