# Generated by Django 4.2 on 2024-11-27 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_remove_ticket_recipt_id_ticket_recipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='receipt_id',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
