# Generated by Django 4.2 on 2025-02-09 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_remove_ticket_schedule_ticket_schedule_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='schedule_group',
        ),
        migrations.AddField(
            model_name='ticket',
            name='drop_schedule',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drop_tickets', to='services.schedule'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='pickup_schedule',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_tickets', to='services.schedule'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('one_way', 'One way'), ('two_way', 'Two way')], default='twoway', max_length=300),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='drop_bus_record',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='drop_tickets', to='services.busrecord'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='drop_point',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_drops', to='services.stop'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='pickup_bus_record',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pickup_tickets', to='services.busrecord'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='pickup_point',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_pickups', to='services.stop'),
        ),
    ]
