# Generated by Django 4.2 on 2024-11-27 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_alter_receipt_receipt_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='student_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='services.studentgroup'),
            preserve_default=False,
        ),
    ]
