# Generated by Django 4.2 on 2025-02-09 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_remove_ticket_schedule_group_ticket_drop_schedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='drop_point',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_drops', to='services.stop'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='pickup_point',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_pickups', to='services.stop'),
        ),
    ]
