# Generated by Django 4.2 on 2025-01-26 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_busrecord_schedule'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='busrecord',
            unique_together={('bus', 'registration', 'schedule')},
        ),
    ]
