# Generated by Django 4.2 on 2025-02-09 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_alter_ticket_drop_point_alter_ticket_pickup_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='drop_bus_record',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='drop_tickets', to='services.busrecord'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='pickup_bus_record',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pickup_tickets', to='services.busrecord'),
        ),
    ]
