# Generated by Django 4.2 on 2025-01-26 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_alter_busrecord_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='bus',
        ),
        migrations.AddField(
            model_name='ticket',
            name='bus_record',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='services.busrecord'),
            preserve_default=False,
        ),
    ]
