# Generated by Django 4.2 on 2024-12-05 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_alter_faq_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='capacity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='BusCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_seats', models.PositiveIntegerField()),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacities', to='services.bus')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_capacities', to='services.registration')),
            ],
            options={
                'unique_together': {('bus', 'registration')},
            },
        ),
    ]
