# Generated by Django 4.2 on 2025-01-26 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_remove_ticket_bus_ticket_bus_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='bus_record',
        ),
        migrations.AddField(
            model_name='ticket',
            name='drop_bus_record',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='drop_tickets', to='services.busrecord'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='pickup_bus_record',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pickup_tickets', to='services.busrecord'),
            preserve_default=False,
        ),
    ]
