# Generated by Django 4.2 on 2025-03-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_alter_ticket_drop_bus_record_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='busrequest',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=20),
        ),
    ]
