# Generated by Django 4.2 on 2024-12-22 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0022_busrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='busrequest',
            old_name='group',
            new_name='student_group',
        ),
    ]
