# Generated by Django 4.2 on 2025-03-09 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0022_alter_busfile_updated_at_alter_faq_updated_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrganisationActivity',
        ),
    ]
