# Generated by Django 4.2 on 2024-12-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0023_rename_group_busrequest_student_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_id',
            field=models.CharField(default=2342, max_length=300),
            preserve_default=False,
        ),
    ]
