# Generated by Django 4.2 on 2024-12-28 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0025_alter_ticket_ticket_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='route_files/')),
                ('added', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_files', to='services.organisation')),
            ],
        ),
    ]
