# Generated by Django 4.2 on 2025-03-14 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0026_alter_notification_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='progress_notification',
            new_name='priority',
        ),
    ]
