# Generated by Django 4.2 on 2024-12-29 09:20

import config.validators
from django.db import migrations, models
import django.db.models.deletion
import services.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0028_alter_routefile_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=services.models.rename_uploaded_file_receipt, validators=[config.validators.validate_csv_file])),
                ('added', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipt_files', to='services.institution')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipt_files', to='services.organisation')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipt_files', to='services.registration')),
            ],
        ),
    ]
