# Generated by Django 4.2 on 2025-03-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0028_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='file_processing_task',
            field=models.BooleanField(default=False),
        ),
    ]
