# Generated by Django 4.2 on 2025-03-19 19:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0030_alter_receipt_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportedfile',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
