# Generated by Django 4.2 on 2025-03-19 19:28

from django.db import migrations, models
import services.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0031_exportedfile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportedfile',
            name='file',
            field=models.FileField(upload_to=services.models.rename_exported_file),
        ),
    ]
