# Generated by Django 4.2 on 2025-06-26 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0033_studentpassfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busrecord',
            name='bus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='services.bus'),
        ),
    ]
