# Generated by Django 4.2 on 2025-10-22 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0034_alter_busrecord_bus'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusReservationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_capacity', models.PositiveIntegerField(help_text='Total number of seats required')),
                ('purpose', models.CharField(help_text='Purpose of the bus reservation', max_length=500)),
                ('date_needed', models.DateField(help_text='Date when buses are needed')),
                ('start_time', models.TimeField(help_text='Start time for the reservation')),
                ('end_time', models.TimeField(help_text='End time for the reservation')),
                ('pickup_location', models.CharField(max_length=500)),
                ('drop_location', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or special requirements', null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_reason', models.TextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reservations', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_reservations', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_reservation_requests', to='services.institution')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_reservation_requests', to='services.organisation')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_reservation_requests', to='services.registration')),
            ],
        ),
        migrations.CreateModel(
            name='BusReservationAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('bus_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_assignments', to='services.busrecord')),
                ('reservation_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_assignments', to='services.busreservationrequest')),
            ],
            options={
                'unique_together': {('reservation_request', 'bus_record')},
            },
        ),
    ]
