# Generated by Django 4.2 on 2025-10-22 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0035_busreservationrequest_busreservationassignment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='busreservationassignment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='busreservationassignment',
            name='bus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reservation_assignments', to='services.bus'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='busreservationassignment',
            unique_together={('reservation_request', 'bus')},
        ),
        migrations.RemoveField(
            model_name='busreservationassignment',
            name='bus_record',
        ),
    ]
