# Generated by Django 4.2 on 2025-10-22 13:42

import datetime
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0036_alter_busreservationassignment_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busreservationrequest',
            name='date_needed',
        ),
        migrations.RemoveField(
            model_name='busreservationrequest',
            name='drop_location',
        ),
        migrations.RemoveField(
            model_name='busreservationrequest',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='busreservationrequest',
            name='pickup_location',
        ),
        migrations.RemoveField(
            model_name='busreservationrequest',
            name='start_time',
        ),
        migrations.AddField(
            model_name='busreservationrequest',
            name='arrival_time',
            field=models.TimeField(default=django.utils.timezone.now, help_text='Arrival time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='busreservationrequest',
            name='booked_by',
            field=models.CharField(default=django.utils.timezone.now, help_text='Name of the person booking', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='busreservationrequest',
            name='contact_number',
            field=models.CharField(default=django.utils.timezone.now, help_text='Contact number of the person booking', max_length=50, validators=[django.core.validators.RegexValidator('^\\d{10,15}$', 'Enter a valid contact number (10-15 digits)')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='busreservationrequest',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date of the reservation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='busreservationrequest',
            name='departure_time',
            field=models.TimeField(default=django.utils.timezone.now, help_text='Departure time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='busreservationrequest',
            name='from_location',
            field=models.CharField(default=django.utils.timezone.now, help_text='Departure location (e.g., SFS School)', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='busreservationrequest',
            name='reservation_no',
            field=models.CharField(blank=True, default=django.utils.timezone.now, help_text='Unique reservation number', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='busreservationrequest',
            name='to_location',
            field=models.CharField(default=django.utils.timezone.now, help_text='Arrival location (e.g., Christ Academy)', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='busreservationrequest',
            name='total_duration',
            field=models.DurationField(default=datetime.timedelta(hours=1), help_text='Total duration of the trip'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='busreservationrequest',
            name='purpose',
            field=models.CharField(blank=True, help_text='Purpose of the bus reservation', max_length=500, null=True),
        ),
    ]
