# Generated by Django 4.2 on 2025-10-22 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0037_remove_busreservationrequest_date_needed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busreservationrequest',
            name='registration',
        ),
    ]
