# Generated by Django 4.2 on 2025-10-31 04:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0038_remove_busreservationrequest_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='busreservationassignment',
            name='driver',
            field=models.ForeignKey(blank=True, limit_choices_to={'profile__is_driver': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='busreservationassignment',
            name='assigned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_assignment_actions', to=settings.AUTH_USER_MODEL),
        ),
    ]
