# Generated by Django 4.2 on 2025-10-31 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0040_make_driver_required_in_bus_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_cost', models.DecimalField(decimal_places=2, default=0.0, help_text='Cost of fuel for the trip', max_digits=10)),
                ('maintenance_cost', models.DecimalField(decimal_places=2, default=0.0, help_text='Cost of maintenance during the trip', max_digits=10)),
                ('toll_charges', models.DecimalField(decimal_places=2, default=0.0, help_text='Toll charges incurred during the trip', max_digits=10)),
                ('driver_bonus', models.DecimalField(decimal_places=2, default=0.0, help_text='Bonus amount to be paid to the driver', max_digits=10)),
                ('other_expenses', models.DecimalField(decimal_places=2, default=0.0, help_text='Any other miscellaneous expenses', max_digits=10)),
                ('total_expense', models.DecimalField(decimal_places=2, default=0.0, editable=False, help_text='Auto-calculated total of all expenses', max_digits=10)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the expenses', null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bus_assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trip_expense', to='services.busreservationassignment')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_expenses_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trip Expense',
                'verbose_name_plural': 'Trip Expenses',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
