# Generated by Django 4.2 on 2025-10-31 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0041_add_trip_expense_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripexpense',
            name='fuel_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Fuel cost for the trip', max_digits=10),
        ),
        migrations.AlterField(
            model_name='tripexpense',
            name='maintenance_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Maintenance expenses during the trip', max_digits=10),
        ),
        migrations.AlterField(
            model_name='tripexpense',
            name='other_expenses',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Other miscellaneous expenses', max_digits=10),
        ),
        migrations.AlterField(
            model_name='tripexpense',
            name='toll_charges',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Toll and tax charges', max_digits=10),
        ),
        migrations.AlterField(
            model_name='tripexpense',
            name='total_expense',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, help_text='Total expense (auto-calculated)', max_digits=10),
        ),
    ]
