# Generated by Django 4.2 on 2025-11-07 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0042_add_trip_expense_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='schedules',
            field=models.ManyToManyField(blank=True, related_name='routes', to='services.schedule'),
        ),
    ]
