# Generated by Django 4.2 on 2025-12-08 05:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0043_route_schedules'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallmentDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveIntegerField(help_text='Installment sequence number (1, 2, 3, etc.)')),
                ('due_date', models.DateField(help_text='Date by which payment should be made')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Expected installment amount', max_digits=10)),
                ('description', models.CharField(blank=True, help_text='Optional description of installment', max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installment_dates', to='services.organisation')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installment_dates', to='services.registration')),
            ],
            options={
                'ordering': ['installment_number', 'due_date'],
                'unique_together': {('registration', 'installment_number')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(db_index=True, help_text='Unique payment identifier', max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=10)),
                ('payment_date', models.DateField(help_text='Date when payment was received')),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('online', 'Online Transfer'), ('upi', 'UPI'), ('card', 'Card'), ('other', 'Other')], default='cash', max_length=20)),
                ('transaction_reference', models.CharField(blank=True, help_text='Transaction ID, cheque number, or other reference', max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the payment')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('installment_date', models.ForeignKey(blank=True, help_text='Associated installment (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='services.installmentdate')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='services.institution')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='services.organisation')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_recorded', to=settings.AUTH_USER_MODEL)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='services.registration')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='services.ticket')),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
    ]
