# Generated by Django 4.2 on 2025-12-08 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0044_installmentdate_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='installmentdate',
            options={'ordering': ['due_date']},
        ),
        migrations.AlterUniqueTogether(
            name='installmentdate',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='installmentdate',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='installmentdate',
            name='installment_number',
        ),
    ]
