# Generated by Django 4.2 on 2025-12-08 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0045_alter_installmentdate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installmentdate',
            name='title',
            field=models.CharField(default='Installment', help_text="Installment title (e.g., 'First Installment', 'Mid-term Payment')", max_length=100),
        ),
    ]
