# Generated by Django 4.2 on 2025-12-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0046_installmentdate_title'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together={('ticket', 'installment_date')},
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('ticket', 'installment_date'), name='unique_ticket_installment_payment', violation_error_message='A payment already exists for this ticket and installment.'),
        ),
    ]
