# Generated by Django 4.2 on 2025-12-12 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0047_alter_payment_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_terminated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='terminated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
