# Generated by Django 4.2 on 2025-12-28 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0048_add_ticket_soft_delete'),
        ('core', '0004_add_role_field_and_migrate_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busreservationassignment',
            name='driver',
            field=models.ForeignKey(help_text='Driver assigned to this bus', limit_choices_to={'profile__role': 'driver'}, on_delete=django.db.models.deletion.PROTECT, related_name='driver_assignments', to=settings.AUTH_USER_MODEL),
        ),
    ]
