# Generated by Django 4.2 on 2025-12-29 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0049_alter_busreservationassignment_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='driver',
        ),
    ]
