# Generated by Django 4.2 on 2025-12-30 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0050_remove_bus_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='busrecord',
            name='assigned_driver',
            field=models.ForeignKey(blank=True, help_text='Driver assigned to this bus record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bus_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='route',
            name='total_km',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total distance of the route in kilometers', max_digits=6, null=True),
        ),
    ]
