# Generated by Django 4.2 on 2026-01-07 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0051_busrecord_assigned_driver_route_total_km'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefuelingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refuel_date', models.DateField()),
                ('fuel_amount', models.DecimalField(decimal_places=2, help_text='Amount in liters or kWh', max_digits=10)),
                ('fuel_cost', models.DecimalField(decimal_places=2, help_text='Total cost', max_digits=10)),
                ('odometer_reading', models.PositiveIntegerField(help_text='Odometer reading in km')),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('cng', 'CNG'), ('electric', 'Electric')], default='diesel', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refueling_records', to='services.bus')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refueling_records', to='services.organisation')),
            ],
            options={
                'verbose_name': 'Refueling Record',
                'verbose_name_plural': 'Refueling Records',
                'ordering': ['-refuel_date', '-created_at'],
            },
        ),
    ]
