# Generated by Django 4.2 on 2026-01-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0052_refuelingrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Only one registration can be active at a time'),
        ),
    ]
