# Generated by Django 4.2 on 2026-01-16 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0053_registration_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='installmentdate',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Expected amount for this installment (optional)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='installmentdate',
            name='institution',
            field=models.ForeignKey(blank=True, help_text='If set, this installment is specific to one institution. If null, it applies to all institutions.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installment_dates', to='services.institution'),
        ),
    ]
