# Generated by Django 4.2 on 2026-01-16 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0054_installmentdate_amount_installmentdate_institution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installmentdate',
            name='amount',
        ),
    ]
