# Generated by Django 4.2 on 2026-01-19 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0055_remove_installmentdate_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='busrequest',
            name='drop_location_map_link',
            field=models.URLField(blank=True, help_text='Google Maps or other map link for the drop location', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='busrequest',
            name='pickup_location_map_link',
            field=models.URLField(blank=True, help_text='Google Maps or other map link for the pickup location', max_length=1000, null=True),
        ),
    ]
