# Generated by Django 5.2 on 2026-02-09 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0058_make_location_map_links_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='drop_bus_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drop_tickets', to='services.busrecord'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='drop_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_drops', to='services.stop'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='drop_schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drop_tickets', to='services.schedule'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='pickup_bus_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pickup_tickets', to='services.busrecord'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='pickup_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_pickups', to='services.stop'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='pickup_schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_tickets', to='services.schedule'),
        ),
    ]
