# Generated by Django 5.2 on 2026-02-10 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0059_alter_ticket_drop_bus_record_alter_ticket_drop_point_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(help_text='Date of the trip')),
                ('actual_pickup_time', models.TimeField(blank=True, help_text='Actual pickup start time', null=True)),
                ('actual_drop_time', models.TimeField(blank=True, help_text='Actual drop completion time', null=True)),
                ('students_picked', models.PositiveIntegerField(blank=True, help_text='Number of students picked up', null=True)),
                ('students_dropped', models.PositiveIntegerField(blank=True, help_text='Number of students dropped', null=True)),
                ('odometer_reading', models.PositiveIntegerField(blank=True, help_text='Odometer reading at trip start (km)', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or observations')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_records', to='services.organisation')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_records', to='services.trip')),
            ],
            options={
                'ordering': ['-record_date', '-created_at'],
                'unique_together': {('trip', 'record_date')},
            },
        ),
    ]
