# Generated by Django 5.2 on 2026-02-10 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0060_triprecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='triprecord',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='triprecord',
            name='bus',
            field=models.ForeignKey(default=1, help_text='Bus for this trip record', on_delete=django.db.models.deletion.CASCADE, related_name='trip_records', to='services.bus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='triprecord',
            name='recorded_by',
            field=models.ForeignKey(default=1, help_text='Driver who recorded this entry', on_delete=django.db.models.deletion.CASCADE, related_name='trip_records', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='triprecord',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_records', to='services.trip'),
        ),
    ]
