# Generated by Django 5.2 on 2026-02-17 05:27

from django.db import migrations, models


def cleanup_duplicate_trip_records(apps, schema_editor):
    """
    Remove duplicate TripRecord entries before applying unique constraint.
    Keeps the most recent record (highest ID) for each (bus, record_date, trip_type) combination.
    """
    TripRecord = apps.get_model('services', 'TripRecord')
    db_alias = schema_editor.connection.alias
    
    # Find all duplicate groups
    from django.db.models import Count
    duplicates = (
        TripRecord.objects.using(db_alias)
        .values('bus_id', 'record_date')
        .annotate(count=Count('id'))
        .filter(count__gt=1)
    )
    
    deleted_count = 0
    for dup in duplicates:
        # Get all records in this duplicate group
        records = TripRecord.objects.using(db_alias).filter(
            bus_id=dup['bus_id'],
            record_date=dup['record_date']
        ).order_by('id')
        
        # Keep the latest record, delete the rest
        records_to_delete = list(records)[:-1]
        for record in records_to_delete:
            record.delete()
            deleted_count += 1
    
    if deleted_count > 0:
        print(f"Cleaned up {deleted_count} duplicate TripRecord(s)")


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0061_alter_triprecord_unique_together_triprecord_bus_and_more'),
    ]

    operations = [
        # First, clean up any duplicate records before schema changes
        migrations.RunPython(cleanup_duplicate_trip_records, reverse_code=migrations.RunPython.noop),
        # Then, remove old fields
        migrations.RemoveField(
            model_name='triprecord',
            name='actual_drop_time',
        ),
        migrations.RemoveField(
            model_name='triprecord',
            name='actual_pickup_time',
        ),
        migrations.RemoveField(
            model_name='triprecord',
            name='odometer_reading',
        ),
        migrations.RemoveField(
            model_name='triprecord',
            name='students_dropped',
        ),
        migrations.RemoveField(
            model_name='triprecord',
            name='students_picked',
        ),
        migrations.RemoveField(
            model_name='triprecord',
            name='trip',
        ),
        # Then, add new fields
        migrations.AddField(
            model_name='triprecord',
            name='actual_time',
            field=models.TimeField(default='00:00:00', help_text='Actual trip start time'),
        ),
        migrations.AddField(
            model_name='triprecord',
            name='end_odometer',
            field=models.PositiveIntegerField(default=0, help_text='Odometer reading at trip end (km)'),
        ),
        migrations.AddField(
            model_name='triprecord',
            name='start_odometer',
            field=models.PositiveIntegerField(default=0, help_text='Odometer reading at trip start (km)'),
        ),
        migrations.AddField(
            model_name='triprecord',
            name='trip_type',
            field=models.CharField(choices=[('pickup', 'Pickup'), ('drop', 'Drop')], default='pickup', help_text='Pickup or Drop', max_length=10),
        ),
        # Then, alter unique_together (now that trip_type exists)
        migrations.AlterUniqueTogether(
            name='triprecord',
            unique_together={('bus', 'record_date', 'trip_type')},
        ),
        # Finally, update model options (now that actual_time exists)
        migrations.AlterModelOptions(
            name='triprecord',
            options={'ordering': ['-record_date', '-actual_time']},
        ),
    ]
