# Generated by Django 5.2 on 2026-02-17 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0061_alter_triprecord_unique_together_triprecord_bus_and_more'),
    ]

    operations = [
        # First, remove old fields
        migrations.RemoveField(
            model_name='triprecord',
            name='actual_drop_time',
        ),
        migrations.RemoveField(
            model_name='triprecord',
            name='actual_pickup_time',
        ),
        migrations.RemoveField(
            model_name='triprecord',
            name='odometer_reading',
        ),
        migrations.RemoveField(
            model_name='triprecord',
            name='students_dropped',
        ),
        migrations.RemoveField(
            model_name='triprecord',
            name='students_picked',
        ),
        migrations.RemoveField(
            model_name='triprecord',
            name='trip',
        ),
        # Then, add new fields
        migrations.AddField(
            model_name='triprecord',
            name='actual_time',
            field=models.TimeField(default='00:00:00', help_text='Actual trip start time'),
        ),
        migrations.AddField(
            model_name='triprecord',
            name='end_odometer',
            field=models.PositiveIntegerField(default=0, help_text='Odometer reading at trip end (km)'),
        ),
        migrations.AddField(
            model_name='triprecord',
            name='start_odometer',
            field=models.PositiveIntegerField(default=0, help_text='Odometer reading at trip start (km)'),
        ),
        migrations.AddField(
            model_name='triprecord',
            name='trip_type',
            field=models.CharField(choices=[('pickup', 'Pickup'), ('drop', 'Drop')], default='pickup', help_text='Pickup or Drop', max_length=10),
        ),
        # Then, alter unique_together (now that trip_type exists)
        migrations.AlterUniqueTogether(
            name='triprecord',
            unique_together={('bus', 'record_date', 'trip_type')},
        ),
        # Finally, update model options (now that actual_time exists)
        migrations.AlterModelOptions(
            name='triprecord',
            options={'ordering': ['-record_date', '-actual_time']},
        ),
    ]
