# Generated by Django 5.2 on 2026-02-17 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0062_simplify_trip_record_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triprecord',
            name='end_odometer',
        ),
        migrations.RemoveField(
            model_name='triprecord',
            name='start_odometer',
        ),
        migrations.AddField(
            model_name='triprecord',
            name='odometer_reading',
            field=models.PositiveIntegerField(default=0, help_text='Odometer reading at time of trip (km)'),
        ),
    ]
