# Generated by Django 5.2 on 2026-02-17 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0063_remove_triprecord_end_odometer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triprecord',
            name='actual_time',
            field=models.TimeField(default='00:00:00', help_text='Time when driver started work (pickup) or completed work (drop)'),
        ),
        migrations.AlterField(
            model_name='triprecord',
            name='odometer_reading',
            field=models.PositiveIntegerField(default=0, help_text='Odometer reading when taking the bus (pickup) or parking it (drop) - in km'),
        ),
        migrations.AlterField(
            model_name='triprecord',
            name='trip_type',
            field=models.CharField(choices=[('pickup', 'Pickup'), ('drop', 'Drop')], default='pickup', help_text='Pickup (when starting work) or Drop (when completing work)', max_length=10),
        ),
    ]
