# Generated by Django 5.2 on 2026-02-27 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0064_alter_triprecord_actual_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='busrequest',
            name='note',
            field=models.TextField(blank=True, help_text='Optional notes or additional comments', null=True),
        ),
    ]
