# Generated by Django 5.2 on 2026-03-05 09:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0065_busrequest_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date when registration was created'),
        ),
    ]
