name: sfs-busnest-project

services:
  app:
    build: ./src
    image: sfs-busnest
    container_name: sfs-busnest-container
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "7000:8000"
    volumes:
      - ./src:/app
    env_file:
      - ./src/config/.env
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres
    container_name: postgres-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: "redis:alpine"
    container_name: redis-container
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  celery:
    image: sfs-busnest
    container_name: sfs-busnest-celery-container
    command: celery -A config worker -E -l info
    volumes:
      - ./src:/app
    env_file:
      - ./src/config/.env
    depends_on:
      - postgres
      - redis
      - app
  
  flower:
    image: sfs-busnest
    container_name: sfs-busnest-flower-container
    command: celery -A config flower --basic_auth=admin:password123
    ports:
      - "5555:5555"
    env_file:
      - ./src/config/.env
    depends_on:
      - redis


volumes:
  postgres_data:
  redis_data:
