name: sfs-busnest-project

services:
  app:
    image: sfs-busnest
    container_name: sfs-busnest-container
    ports:
      - "8001:8000"
    volumes:
      - ./src:/app
  postgres:
    image: postgres
    container_name: postgres-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:
