name: sfs-busnest-project

services:
  app:
    build: ./src
    image: sfs-busnest
    container_name: sfs-busnest-container
    command: sh -c "chmod +x /app/entrypoint.sh"
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres
    container_name: postgres-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: "redis:alpine"
    container_name: redis-container
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  celery:
    image: sfs-busnest
    container_name: sfs-busnest-celery-container
    command: celery -A a_core worker -E -l info
    volumes:
      - ./src:/app
    depends_on:
      - postgres
      - redis
      - app


volumes:
  postgres_data:
  redis_data:
