# Generated by Django 4.2 on 2025-10-24 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_driver',
            field=models.BooleanField(default=False, verbose_name='is driver'),
        ),
    ]
