# Generated by Django 4.2 on 2025-12-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_role_field_and_migrate_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='years_of_experience',
            field=models.PositiveIntegerField(blank=True, help_text='Years of experience (applicable for drivers)', null=True),
        ),
    ]
