# Generated by Django 5.2 on 2026-02-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_years_of_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('central_admin', 'Central Admin'), ('institution_admin', 'Institution Admin'), ('driver', 'Driver'), ('mechanic', 'Mechanic'), ('student', 'Student')], default='student', help_text='Role assigned to this user', max_length=50),
        ),
    ]
